github: [devinschumacher]
open_collective: devinschumacher
custom: [
  "https://apps.serp.co/justforfans-downloader",
  "https://serp.co/products/justforfans-downloader/reviews/",
  "https://extensions.serp.co/justforfans-downloader",
  "https://browserextensions.io/justforfans-downloader"
]
